### ISSUE TITLE
erased_serde::ser::Ok should be public?

### ISSUE THREAD

**Issue by saarw** [dtolnay/erased-serde#11]
I am trying to port code from serde 0.8 to 1.0 with erased_serde 0.3.1 but I am getting stuck on failing to declare a Result with the Ok type because erased_serde::ser is private. Should erased_serde::ser::Ok be made public? Or am I doing something else wrong (that the compiler will tell me about if I got past the module privacy error)?

The code that I have working for serde 0.8 is this
```
use erased_serde::Serialize;   
impl serde::Serialize for Event {  
    fn serialize<S>(&self, serializer: &mut S) -> Result<(), S::Error>  
        where S: serde::Serializer  
    {  
        self.erased_serialize(serializer).map_err(|err| { 
            serde::ser::Error::custom(err.to_string()  
        })
    } 
} 
```

And the code that is failing to compile with serde 1.0.15 and erased serde 0.3.1 is this
```
use erased_serde::{Serialize, Serializer, Error};   
impl serde::Serialize for Event {  
    fn serialize<S>(&self, serializer: S) -> Result<erased_serde::ser::Ok, erased_serde::Error> 
        where S: Serializer 
    { 
        self.erased_serialize(&mut serializer).map_err(|err| { 
            serde::ser::Error::custom(err.to_string()) 
        }) 
    } 
} 
```
Event is a trait that extends erased_serde::Serialize

**Comment by saarw** [comment]
If I instead try to keep S as serde::Serializer and remove the &mut from the method signature, the error I get is "the trait `erased_serde::Serializer` is not implemented for `S`" in the call to erased_serialize.

**Comment by dtolnay** [comment]
I added a macro to help with this in 0.3.2: [`serialize_trait_object!`](https://docs.rs/erased-serde/0.3.2/erased_serde/macro.serialize_trait_object.html)

**Comment by saarw** [comment]
Wow! Above and beyond! Works great! Thanks!
