### ISSUE TITLE
To String Example

### ISSUE THREAD

**Issue by barrettTom** [dtolnay/erased-serde#14]
Hello,

Is it possible to have the serialized information be written to a string? I have been playing around with the library using a Cursor<Vec<u8>> instead of io::stdout() instead but I couldn't get it to compile (I am fairly new to rust).

If so could you please provide an example?

Thanks,
Tom

**Comment by dtolnay** [comment]
It would be almost exactly what you arrived at in IRC except you need the JSON serializer (which borrows &mut buf) to go out of scope before reading from buf.

```rust
extern crate serde_json;
extern crate erased_serde;

use erased_serde::{Serialize, Serializer};

fn main() {
    let mut buf = Vec::new();
    {
        let j = &mut serde_json::Serializer::new(&mut buf);
        let v: Box<Serialize> = Box::new("tomtom");
        v.erased_serialize(&mut Serializer::erase(j)).unwrap();
    }
    println!("{}", String::from_utf8(buf).unwrap());
}
```

**Comment by barrettTom** [comment]
Thanks !
