### ISSUE TITLE
Deserializing boxed trait without knowing what type it is

### ISSUE THREAD

**Issue by CasperN** [dtolnay/erased-serde#25]
Hi, I have an application with a map of trait objects and was wondering how you'd use this crate to deserialize them.  Here is a simplified problem. 
```
#[macro_use]
extern crate serde_derive;
#[macro_use]
extern crate erased_serde;
extern crate serde;
extern crate serde_json;
use std::fmt::Debug;

#[derive(Serialize, Deserialize, Debug)]
struct A;
impl Foo for A{}

#[derive(Serialize, Deserialize, Debug)]
struct B;
impl Foo for B{}

trait Foo: erased_serde::Serialize + Debug {}
serialize_trait_object!(Foo);


fn main() {

    let v: Vec<Box<dyn Foo>> = vec![Box::new(A), Box::new(B), Box::new(A)];
    let s = serde_json::to_string(&v).unwrap();

    let deser = &mut serde_json::de::Deserializer::from_str(&s);
    let mut json = erased_serde::Deserializer::erase(deser);
    let w: Vec<Box<dyn Foo>> =  erased_serde::deserialize(&mut json).unwrap();

    println!("v: {:?}", v);
    println!("w: {:?}", w);

}
```
If I replace `w: Vec<Box<dyn Foo>>` with `w: Vec<Box<A>>` it compiles and runs but is obviously wrong.  Trying to add `serde::Deserialize` to `Foo` leads to lifetimes hell and the inability to use trait objects because 

error[E0038]: the trait

>  `Foo` cannot be made into an object
>   --> src/main.rs:20:1
>    |
> 20 | serialize_trait_object!(<'d>Foo<'d>);
>    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Foo` cannot be made into an object
>    |
>    = note: the trait cannot require that `Self : Sized`
>    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with > -Z external-macro-backtrace for more info)

How would you recommend I implement saving for a container of (among other things) boxed traits?

**Comment by dtolnay** [comment]
You would need to provide an implementation of Deserialize for your trait object:

```rust
use serde::{Deserialize, Deserializer};

trait Foo: erased_serde::Serialize + Debug {}
serialize_trait_object!(Foo);

impl<'de> Deserialize<'de> for Box<dyn Foo> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        /* your implementation here */
    }
}
```

The Deserialize impl can use whatever means makes sense to determine which concrete Foo implementation(s) to produce.

**Comment by CasperN** [comment]
The serialized json string is `[null,null,null]` so the type information is already lost. Do you know how to get the type name into the serialized version? Will that require manually impl serialize?

**Comment by rasky** [comment]
@dtolnay I also would like to deserialize with an erased type. In my case, I already have an object in memory of the correct type, behind a trait object, and I would like to invoke deserialize_in_place on it, using some type erasure magic to make it work through the trait object. Is that possible? Any hint on how to implement it?

**Comment by dtolnay** [comment]
I think @CasperN's use case is addressed by https://github.com/dtolnay/typetag and @rasky's by https://github.com/dtolnay/erased-serde/issues/33.
