### ISSUE TITLE
Can this library be used with `bincode`, `serder_yaml` and `avro_rs`?

### ISSUE THREAD

**Issue by seladb** [dtolnay/erased-serde#26]
If I understand the documentation correctly, this library only works with serde libraries that have a `Serializer` object that implements the `serde::ser::Serializer` trait.

However in `bincode`, `serder_yaml` and `avro_rs` there are no such objects. Can this library be used with them?

**Comment by dtolnay** [comment]
Unfortunately it cannot... We require there to be a Serializer / Deserializer exposed publicly.

**Comment by seladb** [comment]
Thanks! Maybe I can open issues for these 3 libraries to expose this object. I'll close this issue now
