### ISSUE TITLE
Inclusion in serde

### ISSUE THREAD

**Issue by theduke** [dtolnay/erased-serde#3]
Do you think this crate has any change of being included in serde proper?

**Comment by dtolnay** [comment]
Yes! But we are also exploring some alternatives that would be safer and faster. This recent blog post covers one possible alternative:

https://withoutboats.github.io/blog/rust/patterns/traits/2017/01/21/handshake-patterns.html

**Comment by theduke** [comment]
Interesting link, thanks.

Is there a reason why this crate doesn't have a `Deserialize` trait?

**Comment by remram44** [comment]
New URL seems to be https://boats.gitlab.io/blog/post/2017-01-21-handshake-patterns/

**Comment by dtolnay** [comment]
Closing because I've decided against exposing this functionality in serde.
