### ISSUE TITLE
private mod ser

### ISSUE THREAD

**Issue by dmitryvakulenko** [dtolnay/erased-serde#30]
I can't implement Serialize trait for my type because of return value type contain erased_serde::ser::Ok and ser module is private.

**Comment by dtolnay** [comment]
You shouldn't implement erased_serde::Serialize. You should implement serde::Serialize and there is a blanket impl that will turn that into erased_serde::Serialize.

```rust
impl<T> erased_serde::Serialize for T
where
    T: ?Sized + serde::Serialize;
```

**Comment by dmitryvakulenko** [comment]
I don't understand. If I implement serde::Serialize or derive it where shoud I use erased_serde::Serialize?

**Comment by dtolnay** [comment]
After implementing serde::Serialize you get to turn the value into `dyn erased_serde::Serialize`. The readme shows an example of this for `vec!["a", "b"]` and `65536`, both of which have serde::Serialize impls. https://github.com/dtolnay/erased-serde/tree/0.3.10#serialization
