### ISSUE TITLE
Stabilizing erased-serde

### ISSUE THREAD

**Issue by KodrAus** [dtolnay/erased-serde#39]
Hi! :wave:

I was wondering if you had any thoughts on stabilizing `erased-serde`. It seems like it's been doing its thing for a while. Are there any blockers or open questions to consider?

I'm guessing at least trait stability is less of a concern for `erased-serde::{Serialize, Deserialize}` since you can always treat it like one of those trait objects like a regular `serde::{Serialize, Deserialize}`, but having a stable `erased-serde` would be great for those cases where it does appear publicly.

**Comment by dtolnay** [comment]
I assume you are looking for a 1.0 version number. What project does this matter for? I am suspicious of any project having erased-serde's types in a public API, regardless of version number of either library. My impression is typically it would be an internal dependency only.

**Comment by KodrAus** [comment]
So I'm using it [here](https://github.com/sval-rs/value-bag/blob/main/src/internal/serde/v1.rs#L165) as effectively:

```rust
impl From<&dyn erased_serde::Serialize> for SomePublicType {}
```

Which I added under the assumption that `erased-serde`'s traits are what you'd reach for if you want `serde::Serialize`, but trait-object style. There are other similar `From` impls for `SomePublicType` using other traits too, like `Debug` and `Display`. If that's not how you expect them to be used and they should only be hidden internally then I can design around that 🙂

**Comment by dtolnay** [comment]
Could you show an example of how that API is intended to be used? It would basically always require the caller to depend on erased-serde directly, right, in order for the From call to be made unambiguous?

<pre>
<strike>let _ = ValueBag::from(&myval);</strike> // ambiguous
let _ = ValueBag::from(&myval as &dyn erased_serde::Serialize);
</pre>

If so, I think it would be better if you made it an associated method instead with an `&impl serde::Serialize` argument, and handled the conversion to trait object internally.

**Comment by KodrAus** [comment]
Yeh, they actually were inherent methods originally, which I think I'll go back to instead of `From` impls. The `From` impls were added mostly to make an `impl Into<ValueBag>` trait bound as wide as possible, since the goal of that crate is to be able to capture things in as many ways as it can.

Circling back to stabilization it sounds like there's no intention to go down that road just yet. Feel free to close this then unless you'd like to keep it around for the future!
