### ISSUE TITLE
Update to Serde 1.0

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/erased-serde#4]

**Comment by nbigaouette-eai** [comment]
I'm stucked at serde 0.9 until ndarray gets updated too (see https://github.com/bluss/rust-ndarray/issues/314). Could a version for 0.9 be released too?

**Comment by dtolnay** [comment]
There are no difficult differences between 0.9 and 1.0 so I might as well do both. The difficult upgrade for erased-serde is 0.8 to 0.9.

**Comment by nbigaouette-eai** [comment]
That would be awesome thank you!

**Comment by nbigaouette-eai** [comment]
I must say I'm quite lost at trying this; 192 errors just trying to build the tests after changing the toml to serde 0.9 and serde_cbor 0.5...

**Comment by dtolnay** [comment]
Yes it requires a redesign. If you are attempting the upgrade, it will probably be easier to start from scratch than from the 0.8 approach.

**Comment by nbigaouette-eai** [comment]
wow ok... So that's way above my head... :P

**Comment by nbigaouette-eai** [comment]
So until this is implemented, is there another way to serialize/deserialize a trait object?

https://github.com/serde-rs/serde/issues/384 was closed with a reference to this crate...

**Comment by dtolnay** [comment]
I implemented serialization for serde 0.9 in b490bd10774010edf9e7def1a11182d9979efb9c. Working on deserialization for 0.9 next.

**Comment by dtolnay** [comment]
I got serde 0.9 working [here](https://github.com/dtolnay/erased-serde/blob/serde-0.9/tests/readme.rs) and serde 1.0 [here](https://github.com/dtolnay/erased-serde/blob/master/tests/readme.rs). Give it a try! I will aim to get releases out this week.

**Comment by sfackler** [comment]
Wow, I had no idea that was going to be possible!

**Comment by dtolnay** [comment]
I released the serde 0.9 version as erased-serde 0.2.0 and the serde 1.0 version as erased-serde 0.3.0.
