### ISSUE TITLE
Expose all traits within ser and de

### ISSUE THREAD

**Issue by sanbox-irl** [dtolnay/erased-serde#41]
Hello!

I have just made a fork of this project, the sole difference being that it makes public the erased version of the serde helper traits (specifically, I needed MapAccess). I can walk you through an API where that is useful if that helps, but it would be nice if these were made public so I didn't have to maintain a fork (even if it's a pretty silly fork).

A feature flag wouldn't be something I'd mind ofc either!

**Comment by Nic0w** [comment]
Hello there, 
@sanbox-irl, I'm using your fork since it seems I need `Visitor` to be public.
I'm a bit stuck tho because in order to use `Visitor` I need `Out` as well, but its functions are not public.

I second the need of making helper traits (and structs) public ! =)

**Comment by sanbox-irl** [comment]
Hahah, my fork is pretty unsafe. having gotten better at using it, there was some chaos with making stuff work. Mess with care! I can see why it's not public by default.

**Comment by dtolnay** [comment]
I don't think it's sound for those to be public (as you noticed belatedly).

**Comment by Ralith** [comment]
Public interfaces to type-erase `MapAccess` and `SerializeMap` would be helpful to allow use of erased_serde with [the hecs serialization API](https://docs.rs/hecs/0.7.6/hecs/serialize/row/index.html), which is desirable e.g. to support dynamic registration of serialization code.

**Comment by Ralith** [comment]
Should this be reopened to reflect the need, even if the solution is more complex than exporting existing code?
