### ISSUE TITLE
Lifetimed Generics no longer works

### ISSUE THREAD

**Issue by bobyangyf** [dtolnay/erased-serde#55]
Looks like https://github.com/dtolnay/erased-serde/commit/0b99efeb5d6c26fc8160911beb0a4410effe8239
added the `fn __check_erased_serialize_supertrait<__T, $($generics)*>()`
so that if generics contains a lifetime generic, `__T` would be declared before the lifetime, so that it would no longer compile.

**Comment by dtolnay** [comment]
I've published a fix in 0.3.20. Sorry about the breakage!
