### ISSUE TITLE
Deserialize / DeserializeOwned ?

### ISSUE THREAD

**Issue by dakom** [dtolnay/erased-serde#59]
Use case is I have something like this:

```
async fn foo<A: Serialize, B: DeserializeOwned>(args:A) -> B { ... }
```

and I want to store it as a callback to be called later, i.e. something that looks like:

```
struct Callbacks {
    pub foo: Box<dyn Fn(Box<dyn erased_serde::Serialize>) -> Pin<Box<dyn Future<Output=Box<dyn erased_serde::DeserializeOwned>>>>>
}
```

However, erased_serde doesn't have DeserializeOwned. 

Is it possible to add this?

I also brought this up in the Rust forum, in case the surrounding context is helpful in some way: https://users.rust-lang.org/t/how-to-store-callbacks-with-generics/78063/12?u=dakom

**Comment by dtolnay** [comment]
Looks like this got addressed in depth in the forum thread.
