### ISSUE TITLE
Implement `serde::Deserialize` on `Box<dyn MyTrait>`

### ISSUE THREAD

**Issue by tqwewe** [dtolnay/erased-serde#60]
I'm sorry if this may be a duplicate, but I've gone down a bit of a rabbit hole trying to get this to work.

I have a trait `Subscriber` which I need to use as a trait object (`Box<dyn Subscriber>`), but I also require that it implements `Serialize + DeserializeOwned` from serde.
```rust
pub trait Subscriber {
    fn enabled(&self) -> bool;
}
```

I've tried adding `where Self: erased_serde::Serialize`, though it seems like this crate doesn't provide a `Deserialize` trait?
So I attempted to implement it manually:
```rust
impl<'de> Deserialize<'de> for Box<dyn Subscriber> {
    // ...
}
```
Though I'm not sure what I could put for the implementation.

After struggling, I came across the [`typetag`](https://github.com/dtolnay/typetag) crate, but sadly my target is wasm and I am having issues with `ctor`: https://github.com/mmastrac/rust-ctor/issues/14

**Comment by StefanNienhuis** [comment]
Has anyone found a solution for this that’s compatible with WASM?

**Comment by dtolnay** [comment]
Let's centralize discussion of typetag's wasm support in https://github.com/dtolnay/typetag/issues/54.
